on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: venscontainerregistry.azurecr.io
        username: ${{ secrets.acr_venscontainerregistry_username }}
        password: ${{ secrets.acr_venscontainerregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/app" -f  "app/Dockerfile" -t venscontainerregistry.azurecr.io/venskubernetes:${{ github.sha }} --label dockerfile-path=app/Dockerfile
        docker push venscontainerregistry.azurecr.io/venskubernetes:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_venskubernetes_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep venskubernetes99c8 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace venskubernetes99c8`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: venskubernetes99c8
        container-registry-url: venscontainerregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_venscontainerregistry_username }}
        container-registry-password: ${{ secrets.acr_venscontainerregistry_password }}
        secret-name: venskubernetdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: venskubernetes99c8
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          venscontainerregistry.azurecr.io/venskubernetes:${{ github.sha }}
        imagepullsecrets: |
          venskubernetdockerauth
